services:
  load-balancer:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    networks:
      - backend

  backend-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: boscobecker/dotnet-rinha:latest
    container_name: backend-1
    expose:
      - "8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_CONNECTION=redis:6379,abortConnect=false
    networks:
      - backend

  backend-2:
    image: boscobecker/dotnet-rinha:latest
    container_name: backend-2
    expose:
      - "8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_CONNECTION=redis:6379,abortConnect=false
    networks:
      - backend

  redis:
    image: redis:7.2-alpine
    networks:
      - backend

networks:
  backend:
    driver: bridge
